spring:
    application:
        name: spring-practice-auth-server
    threads:
        virtual:
            enabled: true

server:
    port: 9000

management:
    endpoint:
        health:
            probes:
                enabled: true
    health:
        readinessstate:
            enabled: true
        livenessstate:
            enabled: true

jwt:
    issuer-uri: http://${JWT-ISSUER-HOST:localhost}:9000

# Docker container creation command
#   docker run -d --name spring-practice-auth-server -p 9000:9000 spring-practice-auth-server:0.0.1-SNAPSHOT

# Run Auth Server with host name set to (spring-practice-auth-server)
#   docker run -d --name spring-practice-auth-server -h spring-practice-auth-server -e JWT-ISSUER-HOST=spring-practice-auth-server -p 9000:9000 spring-practice-auth-server:0.0.1-SNAPSHOT

# The -h flag sets the hostname of the container to spring-practice-auth-server. This hostname can be useful for networking purposes,
#    especially when the container interacts with other services or containers in a Docker network.