spring:
    application:
        name: spring-practice-auth-server
    threads:
        virtual:
            enabled: true

server:
    port: 9000

management:
    endpoint:
        health:
            probes:
                enabled: true
    health:
        readinessstate:
            enabled: true
        livenessstate:
            enabled: true